### ISSUE TITLE
Docker-compose fails with mkdir /var/druid and /var/tmp, permission denied

### ISSUE THREAD

**Issue by Ycallaer** [apache/druid#10908]
### Affected Version

Druid version 0.21.0
Build on Ubuntu 20.04LTS

### Description

After building the image as described [here](https://github.com/apache/druid/tree/0.20.1/distribution/docker), I start the docker with the following command:
`docker-compose -f distribution/docker/docker-compose.yml up`

After a lot of initial messages both historical and router start complaining that they don't have permissions to create certain directories

```
router           | mkdir: can't create directory 'var/tmp': Permission denied
router           | mkdir: can't create directory 'var/druid/': Permission denied
router           | mkdir: can't create directory 'var/druid/': Permission denied
router           | mkdir: can't create directory 'var/druid/': Permission denied
router           | mkdir: can't create directory 'var/druid/': Permission denied
router           | mkdir: can't create directory 'var/druid/': Permission denied
middlemanager    | Setting druid.indexer.logs.directory=/opt/data/indexing-logs in /tmp/conf/druid/cluster/data/middleManager/runtime.properties
broker           | mkdir: can't create directory 'var/tmp': Permission denied
broker           | mkdir: can't create directory 'var/druid/': Permission denied
broker           | mkdir: can't create directory 'var/druid/': Permission denied
broker           | mkdir: can't create directory 'var/druid/': Permission denied
broker           | mkdir: can't create directory 'var/druid/': Permission denied
broker           | mkdir: can't create directory 'var/druid/': Permission denied

```
In the end, the following services abort with an exit code 1
```
historical exited with code 1
router exited with code 1
broker exited with code 1
middlemanager exited with code 1
```

I am new to druid and I am just following the quickguide.

Any ideas what might be the root cause ?

**Comment by anand-venda** [comment]
Me to getting the same problem

**Comment by FrankChen021** [comment]
resolved by #11166 
Thanks

**Comment by fiantinangon** [comment]
Hi @FrankChen021 i still facing the same problem with this issue, 
Using this docker compose from latest documentation page 
https://github.com/apache/druid/blob/0.21.0/distribution/docker/docker-compose.yml
 
![Screen Shot 2021-05-19 at 15 30 48](https://user-images.githubusercontent.com/9161278/118781654-7ec07480-b8b7-11eb-945b-33d15ff5da94.png)

**Comment by FrankChen021** [comment]
Hi @fiantinangon , this bug will be fixed in 0.21.1 which is being in the release process. I think the new version will be published in a couple of days.

**Comment by fiantinangon** [comment]
> Hi @fiantinangon , this bug will be fixed in 0.21.1 which is being in the release process. I think the new version will be published in a couple of days.

Ok @FrankChen021 thanks for the information looking forward for the new release

**Comment by RexterR** [comment]
Is it Published? If not then, Why this issue is closed?
